MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 96264
  HEADS:
    IN_FEAT: 2048
    REDUCTION_DIM: 512
    MARGIN: 0.15
    SCALE: 30
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.01
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: landmark
  SPLIT: train_list.txt
  BATCH_SIZE: 64
  IM_SIZE: 224
  EVAL_PERIOD: 100
TEST:
  DATASET: landmark
  SPLIT: val_list.txt
  BATCH_SIZE: 64
  IM_SIZE: 256
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4 
CUDNN:
  BENCHMARK: True
OUT_DIR: ./output
